project/apps/schedule/urls.py
from django.conf.urls import url
from apps.schedule.views import ListSchedule, create_appointment, ListPacients, UpdatePacient, AppointmentAPI, PacientsAPI
urlpatterns = [
    url(r'^$', ListSchedule.as_view(), name="index"),
    url(r'create_appointment$', create_appointment, name="create_appointment"),
    url(r'admin_pacients', ListPacients.as_view(), name="admin_pacients"),
    url(r'^pacient/edit/(?P<pk>\d+)$', UpdatePacient.as_view(), name='update_pacient'),
    url(r'services/appointment', AppointmentAPI.as_view()),
    url(r'services/pacients', PacientsAPI.as_view()),
]

project/project/urls.py
from django.conf.urls import url, include
from apps.schedule import urls as schedule_urls

urlpatterns = [
    url(r'^', include(schedule_urls, namespace="schedule")),
]

project/apps/schedule/models.py
from django.db import models

class appointment_types(models.Model):
    type = models.CharField(max_length=20)

class pacient(models.Model):
    name = models.CharField(max_length=80)
    birth_date = models.DateField()
    telephone = models.CharField(max_length=15)

class appointment(models.Model):
    date = models.DateTimeField()
    type = models.ForeignKey(appointment_types, default=None)
    pacient = models.ForeignKey(pacient, default=None)

project/apps/schedule/forms.py
from django import forms
from apps.schedule.models import appointment, appointment_types, pacient
from django.contrib.admin import widgets

class create_appointment_form(forms.ModelForm):
    date = forms.TextInput(attrs={'class': 'datepicker'})
    class Meta:
        model = appointment
        fields = [
            'date',
            'type',
            'pacient',
        ]
        labels = {
            'date': 'Fecha de la cita:',
            'type': 'Tipo de cita:',
            'pacient' : 'Paciente asociado:',
        }

    def __init__(self, *args, **kwargs):
        super(create_appointment_form, self).__init__(*args, **kwargs)
        types = []
        query = appointment_types.objects.all().values_list('id', flat=True)
        for id in query:
            types.append((id, appointment_types.objects.get(id=id).type))
        types = tuple(types)
        self.fields["type"].widget = forms.widgets.RadioSelect(choices=types)
        pacients=[]
        query = pacient.objects.all().values_list('id', flat=True)
        for id in query:
            pacients.append((id, pacient.objects.get(id=id).name))
        pacients = tuple(pacients)
        self.fields["pacient"].widget = forms.widgets.RadioSelect(choices=pacients)

class PacientForm(forms.ModelForm):

	class Meta:
		model = pacient
		fields = [
			'name',
			'birth_date',
			'telephone',
		]
		labels = {
			'name': 'Nombres:',
			'birth_date': 'Fecha de nacimiento',
			'telephone': 'Edad',
		}
		widgets = {
			'name':forms.TextInput(attrs={'class':'form-control'}),
            'birth_date': forms.TextInput(attrs={'type': 'date'}),
			'telephone':forms.TextInput(attrs={'class':'form-control'}),
        }

project/apps/schedule/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from django.views.generic import CreateView, ListView, UpdateView
from apps.schedule.models import appointment, pacient
from apps.schedule.forms import create_appointment_form, PacientForm
from django.core.urlresolvers import reverse_lazy
from apps.schedule.serializers import AppointmentSerializer, PacientSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
import datetime
import json

class ListSchedule(ListView):
    model = appointment
    template_name = 'schedule_templates/schedule.html'

    def get_queryset(self):
        objects = appointment.objects.order_by("date")
        for obj in objects:
            if(obj.date.date() < datetime.datetime.now().date()):
                obj.delete()
        return objects


def check_date(date):
    checked=True
    list_appointments = appointment.objects.all()
    attention_time = date + datetime.timedelta(minutes=-15)
    for appointment_x in list_appointments:
        if(date.date() == appointment_x.date.date()):
            if((date.hour == appointment_x.date.hour and date.minute == appointment_x.date.minute) or (attention_time.hour == appointment_x.date.hour and attention_time.minute <= appointment_x.date.minute)):
                checked=False
    if(checked):
        return True
    else:
        return False


class AppointmentAPI(APIView):
    serializer = AppointmentSerializer

    def get(self, request, format=None):
        objects = appointment.objects.all()
        response = self.serializer(objects, many=True)
        return Response(response.data, status=status.HTTP_200_OK)

class PacientsAPI(APIView):
    serializer = PacientSerializer

    def get(self, request, format=None):
        objects = pacient.objects.all()
        response = self.serializer(objects, many=True)
        return Response(response.data, status=status.HTTP_200_OK)

class ListPacients(ListView):
    model = pacient
    template_name = 'schedule_templates/admin_pacients.html'

class UpdatePacient(UpdateView):
    model = pacient
    template_name = 'schedule_templates/update_pacient.html'
    form_class = PacientForm
    success_url = reverse_lazy('schedule:admin_pacients')

    def get_context_data(self, **kwargs):
        context = super(UpdatePacient, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        if 'form' not in context:
            context['form'] = self.form_class()
        context['id'] = pk
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        id_solicitud = kwargs['pk']
        solicitud = self.model.objects.get(id=id_solicitud)
        form = self.form_class(request.POST, instance=solicitud)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

def create_appointment(request):
    if request.method == "GET":
        today = datetime.datetime.now()
        form = create_appointment_form()
        return render(request, "schedule_templates/create_appointment.html", {"form": form, "date_today" : today.date().isoformat()})
    elif(request.method == "POST"):
        form = create_appointment_form(request.POST)
        date = request.POST.get("date").split("-")
        time = request.POST.get("time").split(":")
        if(len(time) <= 2):
            time.append("00")
        try:
            datetime_value = datetime.datetime(
                                                int(date[0]),int(date[1]),int(date[2]),
                                                int(time[0]), int(time[1], int(time[2]))
                                              )
            if(check_date(datetime_value)):
                if(datetime_value.date() >= datetime.datetime.now().date()):
                    solicitud = form.save(commit=False)
                    solicitud.date = datetime_value
                    solicitud.save()
                    form.save_m2m()
                    return redirect("schedule:index")
                else:
                    form.errors["date"] = " Estas agendando una cita antes de la fecha de hoy "
                    return render(request, "schedule_templates/create_appointment.html",
                                  {"form": form, "date_today": datetime.datetime.now().date})
            else:
                form.errors["date"] = " Ya hay una cita asignada en ese intervalo "
                return render(request, "schedule_templates/create_appointment.html", {"form": form, "date_today" : datetime.datetime.now().date})
        except:
            return render(request, "schedule_templates/create_appointment.html", {"form": form, "date_today" : datetime.datetime.now().date})

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Dashboard - Dr. Mark</title>
  {% load staticfiles %}
  <link href="{% static 'global/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'global/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'global/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
  <link href="{% static 'global/css/sb-admin.css' %}" rel="stylesheet">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'schedule:index' %}">Agenda digital</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right">
          <a class="nav-link" href="{% url 'schedule:index' %}">
            <i class="fa fa-fw fa-address-book"></i>
            <span class="nav-link-text">Listado de citas</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right">
          <a class="nav-link" href="{% url 'schedule:create_appointment' %}">
            <i class="fa fa-fw fa-edit"></i>
            <span class="nav-link-text">Agendar cita</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right">
          <a class="nav-link" href="{% url 'schedule:admin_pacients' %}">
            <i class="fa fa-fw fa-universal-access"></i>
            <span class="nav-link-text">Listar pacientes</span>
          </a>
        </li>
      </ul>
        <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
        </ul>

    </div>
  </nav>
  <div class="content-wrapper">
  {% block wrapper_content %}{% endblock %}
  </div>
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
        </div>
      </div>
    </footer>

    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    {% block script %}{% endblock %}


    <script src="{% static 'global/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'global/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'global/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'global/vendor/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'global/vendor/datatables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'global/vendor/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'global/js/sb-admin.min.js' %}"></script>
    <script src="{% static 'global/js/sb-admin-datatables.min.js' %}"></script>
    <script src="{% static 'global/js/sb-admin-charts.min.js' %}"></script>
  </div>
</body>

</html>

project/templates/schedule_templates/admin_pacients.html
{% extends "base.html" %}

{% block wrapper_content %}
<div align="center">
	<h2>Lista de pacientes</h2>
</div>
<table class="table table-bordered">
	{% if object_list %}
	<thead>
		<tr>
			<td>Nombres</td>
			<td>Fecha de nacimiento</td>
			<td>Telefono</td>
		</tr>

	</thead>
	<tbody>
		{% for solicitud in object_list %}
		<tr>
			<td>{{ solicitud.name }}</td>
			<td>{{ solicitud.birth_date }}</td>
			<td>{{ solicitud.telephone }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'schedule:update_pacient' solicitud.id %}">Editar</a>
			</td>
		</tr>
		{% endfor %}

	{% else %}
	<h1>No se encontraron registros</h1>
	{% endif %}
	</tbody>
</table>
{% endblock %}

project/templates/schedule_templates/create_appointment.html
{% extends "base.html" %}

 {% block wrapper_content %}
<div style="margin: 0 auto;text-align: left;width: 1000px;">
    <h1> Nueva cita </h1>
    <form method="post">
        {% csrf_token %}
        <div><b>{{ form.date.label }}</b></div>
        <input name="date" type="date" value = "{{ date_today }}"> <input name="time" type="time" value="08:00:00" step="1">
        {% if form.errors.date %}
            <div class="alert alert-danger">
                <strong>•</strong>{{ form.errors.date }}
            </div>
        {% endif %}
        <div><b>{{ form.type.label }}</b> </div>

        {% for element in form.type %}
            <div>
                {{ element }}
            </div>
        {% endfor %}
        {% if form.errors.type %}
            <div class="alert alert-danger">
                {{ form.errors.type }}
            </div>
        {% endif %}
        <div><b>{{ form.pacient.label }}</b> </div>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Pacientes
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <table>
               <tr>
                  {% for com in form.pacient %}
                    {% if forloop.counter0|divisibleby:"3" %}
                        </tr>
                    {% endif%}
                    <td>{{ com }}</td>
                  {% endfor %}
           </table>
          </div>
          {% if form.errors.pacient %}
            <div class="alert alert-danger">
                {{ form.errors.pacient }}
            </div>
          {% endif %}
        </div>

        <div style=" margin-top:20px;"><button type="submit" class="btn btn-primary">Añadir</button></div>
    </form>
</div>
{% endblock %}

project/templates/schedule_templates/schedule.html
{% extends "base.html" %}


{% block wrapper_content %}
<table class="table table-bordered">
	{% if object_list %}
	<thead>
		<tr>
			<td>Fecha y hora</td>
			<td>Tipo de cita</td>
			<td>Paciente</td>
		</tr>

	</thead>
	<tbody>
		{% for solicitud in object_list %}
		<tr>
			<td>{{ solicitud.date }}</td>
			<td>{{ solicitud.type.type }}</td>
			<td>{{ solicitud.pacient.name }}</td>
		</tr>
		{% endfor %}

	{% else %}
	<h1>No se encontraron registros</h1>
	{% endif %}
	</tbody>
</table>
{% endblock %}

project/templates/schedule_templates/update_pacient.html
{% extends "base.html" %}


{% block wrapper_content %}
<div style="margin: 0 auto;text-align: left;width: 1000px;">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div style=" margin-top:20px;"><button type="submit" class="btn btn-primary">Actualizar</button></div>
    </form>
</div>
{% endblock %}